-- Processed Events (for idempotency)
CREATE SEQUENCE CMS_PROC_SEQ START WITH 1 INCREMENT BY 1 CACHE 1000 NOCYCLE;

CREATE TABLE CMS_PROCESSED_EVENTS (
    EVENT_ID     VARCHAR2(100) PRIMARY KEY,
    PAYLOAD_HASH VARCHAR2(128),
    STATUS       VARCHAR2(20),
    PROCESSED_AT TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

-- Indexes for Processed Events
CREATE INDEX IDX_CMS_PROC_STATUS ON CMS_PROCESSED_EVENTS(STATUS);
