-- Seed Accounts
INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (1, 'ACTIVE', 5000, 0, 5000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (2, 'ACTIVE', 3000, 0, 3000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (3, 'ACTIVE', 4000, 0, 4000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (4, 'CLOSED', 2000, 0, 2000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (5, 'BLOCKED', 6000, 0, 6000);
