-- Add merchantId column to CMS_TRANSACTIONS table
ALTER TABLE CMS_TRANSACTIONS ADD MERCHANT_ID NUMBER(19);

-- Add index for better query performance
CREATE INDEX IDX_CMS_TXN_MERCHANT_ID ON CMS_TRANSACTIONS(MERCHANT_ID);

-- Add foreign key constraint to CMS_ACCOUNTS table
ALTER TABLE CMS_TRANSACTIONS ADD CONSTRAINT FK_CMS_TXN_MERCHANT_ACCOUNT 
    FOREIGN KEY (MERCHANT_ID) REFERENCES CMS_ACCOUNTS(ACCOUNT_ID);
