-- Seed additional merchants & issuer accounts required for promotions referenced in creditPromoServ
INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, ACCOUNT_TYPE, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (1001, 'MERCHANT', 'ACTIVE', 15000, 0, 15000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, ACCOUNT_TYPE, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (1002, 'MERCHANT', 'ACTIVE', 12000, 0, 12000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, ACCOUNT_TYPE, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (1003, 'MERCHANT', 'ACTIVE', 18000, 0, 18000);

-- Companion issuer accounts used in promo tests
INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, ACCOUNT_TYPE, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (7001, 'ISSUER', 'ACTIVE', 8000, 0, 8000);

INSERT INTO CMS_ACCOUNTS (CUSTOMER_ID, ACCOUNT_TYPE, STATUS, AVAILABLE_BALANCE, RESERVED, CREDIT_LIMIT)
VALUES (7002, 'ISSUER', 'ACTIVE', 9000, 0, 9000);
